import Head from 'next/head'
import Navbar from '@/components/Navbar.jsx'
import Homepage from '../sections/home.jsx'
import OurMenu from '@/sections/menu.jsx'
import Deserts from '@/sections/deserts.jsx'
import AboutUs from '@/sections/about.jsx'
import ContactUs from '@/sections/contact.jsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>TheCoffeeShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
        </Head>
      <Homepage />
      <OurMenu />
      <Deserts />
      <AboutUs />
      <ContactUs />
    </>
  )
}
